# Generated by Django 4.2.4 on 2023-08-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_home_file_alter_home_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_of_experiance', models.CharField(max_length=50)),
            ],
        ),
    ]
