# Generated by Django 4.2.4 on 2023-08-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_aboutme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutME',
        ),
        migrations.AddField(
            model_name='home',
            name='years_of_experiance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
