# Generated by Django 4.2.4 on 2023-08-24 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_delete_aboutme_home_years_of_experiance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name_plural': 'Home'},
        ),
    ]
