# Generated by Django 4.2.4 on 2023-08-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_rename_time_timeline_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='title',
            field=models.CharField(default='Linkedin', max_length=50),
            preserve_default=False,
        ),
    ]
